### PR TITLE
build.sh: add pmufw-clean

### PR DESCRIPTION
**Pull request by nealfrager**
This patch adds support for cleaning the pmufw.  It improves the ease of use of the script for users who make modifications to the pmufw.

### CODE REVIEW

**Comment by nealfrager** [comment]
Hi Luca, 

While working on the zynqmp-pmufw-builder and testing the options, I often needed to clean the pmufw, so I could run another test with the build.sh script.  To speed things up, I added the pmufw-clean option, so that I would not need to manually clean the pmufw each time.  Now that I think about it, I think users of the zynqmp-pmufw-builder might find this capability useful as well.  Especially if they choose to make changes to the pmufw or add some additional build configurations.  What do you think?  Are you ok with adding this feature?

Best regards,
Neal Frager
AMD

**Comment by lucaceresoli** [comment]
Hi Neal,
thanks, it's a very good idea!
I added some comments inline though, those should allow for a much simpler path.
Luca

**Comment by nealfrager** [comment]
Hi Luca,
I am not sure what comments you are referring to.  In any case, feel free to update my pmufw-clean patch if you have another way you would like to do it.  As long as the clean can be done with a simple build.sh command, it is fine for me.  Thanks!

Best regards,
Neal Frager
AMD

**Comment by lucaceresoli** [comment]
My comments are visible in the github pull request page, they don't seem to be
added to e-mails.

I have applied the changes and pushed to master, thanks!

In reality I'm not sure the pmufw-clean command is useful when you edit the sources: when you do, just using `./build.sh pmufw-build` will run the build. However I often ended up in doing the cleanup manually by typing a shell command, thus I think it is useful anyway.

Luca

**Pull request closed without merging**
